spring:
  application:
    name: component
  datasource:
    username: root
    password: Xjy123456
    url: jdbc:mysql://localhost:3306/traderplatform
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid ?????
    druid:
      # ?????????????
      initial-size: 5
      # ??????????
      min-idle: 5
      # ?????????
      max-active: 20
      # ????????????????
      max-wait: 60000


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.xiaojingye.wechatbackend.component.mapper: debug

es:
  port: 9200
  host: 127.0.0.1

